variables:
  KUBERNETES_CPU_REQUEST: 2
  RUNNER_REQUEST_CONCURRENCY: 2 # I think KUBERNETES_CPU_REQUEST x RUNNER_REQUEST_CONCURRENCY should be less than 8
  KUBERNETES_MEMORY_REQUEST: 4Gi

  # DOCKER_TLS_CERTDIR: "/certs"
  # DOCKER_TLS_VERIFY: 1
  # DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
      - yarn.lock

  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

stages:
  - build
  - test

build:
  stage: build
  # use podman to build without needing DIND / docker daemon service
  image: quay.io/podman/stable
  script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - podman build -f docker/e2e.Dockerfile -t $CI_REGISTRY_IMAGE:latest .
    - podman push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $TEST == ""
      changes: # I don't see this working?
        - docker/e2e.Dockerfile

.tests:
  stage: test
  image: $CI_REGISTRY_IMAGE:latest
  before_script:
    - yarn install --immutable
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"


  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day

nextcloud_aws:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/aws*nextcloud*.js'
  rules:
    - if: $TEST == "nextcloud" || $TEST == "nextcloud_aws" || $TEST == "all"

nextcloud_gcp:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/gcp*nextcloud*.js'
  rules:
    - if: $TEST == "nextcloud" || $TEST == "nextcloud_gcp" || $TEST == "all"

nextcloud_do:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/do*nextcloud*.js'
  rules:
    - if: $TEST == "nextcloud" || $TEST == "nextcloud_do" || $TEST == "all"

baserow:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/*baserow*.js'
  rules:
    - if: $TEST =~ /baserow/ || $TEST == "all"

minecraft:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/*minecraft*.js'
  rules:
    - if: $TEST =~ /minecraft/ || $TEST == "all"

container_webapp:
  extends: .tests
  script:
    - EXTERNAL=0 yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/*container-webapp*.js'
  rules:
    - if: $TEST == "container_webapp" || $TEST == "all"

container_webapp_gcp:
  extends: .tests
  script:
    - EXTERNAL=0 yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/gcp__container-webapp*.js'
  rules:
    - if: $TEST == "container_webapp_gcp"

container_webapp_aws:
  extends: .tests
  script:
    - EXTERNAL=0 yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/aws__container-webapp*.js'
  rules:
    - if: $TEST == "container_webapp_aws"

ghost:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/*ghost*.js'
  rules:
    - if: $TEST =~ /ghost/ || $TEST == "all"

mediawiki:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/*mediawiki*.js'
  rules:
    - if: $TEST =~ /mediawiki/ || $TEST == "all"

wordpress:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/*wordpress*.js'
  rules:
    - if: $TEST =~ /wordpress/ || $TEST == "all"

kubernetes:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s './cypress/e2e/blueprints/k8s*.js'
  rules:
    - if: $TEST =~ /k8s/ || ($TEST == "all" && $SKIP !~ /k8s/)

unfurl_cloud_dns:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -e USE_UNFURL_DNS=opencloudservices.net -s './cypress/e2e/blueprints/aws__nextcloud__only-mail*.js'
  rules:
    - if: $TEST =~ /uc_dns/ || $TEST == "all"

# These tests normally run with their respective blueprints
cloud_redis:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s cypress/e2e/blueprints/gcp__nextcloud__memorystore*.js,cypress/e2e/blueprints/aws__nextcloud__memorydb*.js
  rules:
    - if: $TEST == "cloud_redis"

# Not yet fully supported for $TEST == "all"
multiple_workflows:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s cypress/e2e/deployments/multiple-workflows*.js
  rules:
    - if: $TEST == "multiple_workflows"

shared_volumes:
  extends: .tests
  script:
    - yarn run integration-test run --namespace onecommons/blueprints -- --browser chrome -s cypress/e2e/deployments/shared-volume*.js
  rules:
    - if: $TEST == "shared_volumes" || $TEST == "all"

