name: CI

on: [push]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    env:
      UNFURL_BRANCH: standalone-gui
      AWS_DNS_ZONE: opencloudservices.net 
      AWS_ACCESS_KEY_ID: foobarbaz
      AWS_SECRET_ACCESS_KEY: asldfjkasldkjalqweioptuqpeortiu
      AWS_DEFAULT_REGION: eu-central-1
      MAIL_USERNAME: admin@mailu.untrusted.me
      MAIL_PASSWORD: ocPC2cnGkQsz35I
      SMTP_HOST: mailu.untrusted.me
      CY_COMMAND_TIMEOUT: 30000
      TEST_VERSIONS: v2
      UNFURL_TEST_TMPDIR: tmp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn dependencies
        run: npm i -g yarn && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
        # TODO add back ufsv-patch -- --runInBand
      - name: Run unit tests
        run: yarn test packages -- --runInBand
      - name: Compile
        run: yarn build
      - name: Install unfurl
        run: git clone --recurse-submodules --branch $UNFURL_BRANCH --single-branch --depth 1 https://github.com/onecommons/unfurl $HOME/unfurl; pip install -e $HOME/unfurl
      - name: Integration test
        run: yarn integration-test run --namespace onecommons/blueprints -- -e GENERATE_SUBDOMAINS=true --browser chrome -s cypress/e2e/blueprints/aws__baserow__baserow.cy.js
      - name: Upload Cypress screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload dashboard
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: dashboard
          path: ${{ env.UNFURL_TEST_TMPDIR }}/ufsv
      - name: Upload unfurl server log
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unfurl-server-log
          path: ${{ env.UNFURL_TEST_TMPDIR }}/unfurl.log
      - name: Create release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -czvf unfurl-gui-dist.tar.gz dist
      - name: Upload release artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: unfurl-gui-dist
          path: unfurl-gui-dist.tar.gz
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: unfurl-gui-dist
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: unfurl-gui-dist.tar.gz
