name: Cypress CI

on:
  push:
    branches: [ cypress-actions-ci ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: serve # will run `yarn serve` command
