name: Cypress CI

on: [push]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2.5.1
      - name: Install yarn dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Run unit tests
        run: yarn test
      - name: Update Unfurl
        run: pip3 install -U  "git+https://github.com/onecommons/unfurl.git#egg=unfurl"
      - name: Run apollo and serve
        run: yarn start
      - name: Run Cypress
        run: xargs yarn run cypress run -C cypress-ci.json -s  < cypress/ci-tests.txt
      - name: Archive test screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            cypress/screenshots/
      - name: Archive test videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: |
            cypress/videos/


