name: Cypress CI

on: [push]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2.5.1
      - name: Install node, yarn
        run: npm install --global yarn
      - name: Install yarn dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Run unit tests
        run: yarn test
      - name: Run apollo and serve
        run: yarn start
      - name: Install Cypress dependencies
        run: sudo apt-get update --fix-missing && sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

      - name: Add Cypress
        run: yarn add cypress
      - name: Run Cypress
        run: xargs yarn run cypress run -s  < cypress/ci-tests.txt
      - name: Archive test screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: |
            cypress/screenshots/
      - name: Archive test videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: |
            cypress/videos/


