name: Cypress CI

on:
  push:
    branches: [ cypress-actions-ci ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
      - name: Install node, yarn
        run: npm install --global yarn
      - name: Install yarn dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Run server
        run: yarn run serve &
      - name: Add Cypress
        run: yarn add cypress
      - name: Run Cypress
        run: yarn cypress run -e OC_URL="http://0.0.0.0:8081",OC_NAMESPACE="root",OC_USERNAME="root",OC_PASSWORD="c6uRYQKrLuxNCd8"


