name: Cypress CI

on:
  push:
    branches: [ cypress-actions-ci ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install node
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
      - run: npm install --global yarn
      - name: Install yarn
        run: yarn install


