name: Release

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/') }}
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: unfurl-gui-dist
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: unfurl-gui-dist.tar.gz
